<?php

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Dashboard',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2018-01-23 12:45:58',
                'updated_at' => '2018-01-23 12:45:58',
                'route' => 'voyager.dashboard',
                'parameters' => NULL,
            ),
            
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2018-01-23 12:45:58',
                'updated_at' => '2018-02-14 16:05:20',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Posts',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-news',
                'color' => NULL,
                'parent_id' => 8,
                'order' => 7,
                'created_at' => '2018-01-23 12:45:58',
                'updated_at' => '2018-02-14 16:05:54',
                'route' => 'voyager.posts.index',
                'parameters' => NULL,
            ),
            
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-group',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2018-01-23 12:45:58',
                'updated_at' => '2018-02-14 16:05:20',
                'route' => 'voyager.users.index',
                'parameters' => 'null',
            ),
            
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Categories',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-categories',
                'color' => NULL,
                'parent_id' => 8,
                'order' => 8,
                'created_at' => '2018-01-23 12:45:58',
                'updated_at' => '2018-02-14 16:05:55',
                'route' => 'voyager.categories.index',
                'parameters' => NULL,
            ),
            
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Pages',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-file-text',
                'color' => NULL,
                'parent_id' => 8,
                'order' => 9,
                'created_at' => '2018-01-23 12:45:58',
                'updated_at' => '2018-02-14 16:05:57',
                'route' => 'voyager.pages.index',
                'parameters' => NULL,
            ),
            
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => 8,
                'order' => 2,
                'created_at' => '2018-01-23 12:45:58',
                'updated_at' => '2018-02-14 16:16:07',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Developer Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2018-01-23 12:45:58',
                'updated_at' => '2018-02-14 16:05:44',
                'route' => NULL,
                'parameters' => '',
            ),
            
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 8,
                'order' => 4,
                'created_at' => '2018-01-23 12:45:58',
                'updated_at' => '2018-02-14 16:16:00',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 8,
                'order' => 1,
                'created_at' => '2018-01-23 12:45:58',
                'updated_at' => '2018-02-14 16:16:07',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 8,
                'order' => 3,
                'created_at' => '2018-01-23 12:45:58',
                'updated_at' => '2018-02-14 16:15:59',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            
            array (
                'id' => 12,
                'menu_id' => 1,
                'title' => 'Settings',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => 8,
                'order' => 6,
                'created_at' => '2018-01-23 12:45:58',
                'updated_at' => '2018-02-14 16:05:20',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            
            array (
                'id' => 13,
                'menu_id' => 1,
                'title' => 'Hooks',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-hook',
                'color' => NULL,
                'parent_id' => 8,
                'order' => 5,
                'created_at' => '2018-01-23 12:46:12',
                'updated_at' => '2018-02-14 16:16:00',
                'route' => 'voyager.hooks',
                'parameters' => NULL,
            ),
            
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'Driver Options',
                'url' => '/admin/driver-options',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 18,
                'order' => 1,
                'created_at' => '2018-01-23 13:08:00',
                'updated_at' => '2018-01-24 07:55:45',
                'route' => NULL,
                'parameters' => NULL,
            ),
            
            array (
                'id' => 15,
                'menu_id' => 1,
                'title' => 'Driver Details',
                'url' => '/admin/driver-details',
                'target' => '_self',
                'icon_class' => 'voyager-book',
                'color' => '#000000',
                'parent_id' => 18,
                'order' => 2,
                'created_at' => '2018-01-23 13:43:44',
                'updated_at' => '2018-01-24 07:55:45',
                'route' => NULL,
                'parameters' => '',
            ),
            
            array (
                'id' => 16,
                'menu_id' => 1,
                'title' => 'Vehicles',
                'url' => '/admin/vehicles',
                'target' => '_self',
                'icon_class' => 'voyager-params',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2018-01-23 13:54:46',
                'updated_at' => '2018-02-14 16:05:20',
                'route' => NULL,
                'parameters' => NULL,
            ),
            
            array (
                'id' => 17,
                'menu_id' => 1,
                'title' => 'Verification Messages',
                'url' => '/admin/verification-messages',
                'target' => '_self',
                'icon_class' => 'voyager-chat',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2018-01-23 13:58:38',
                'updated_at' => '2018-02-14 16:05:20',
                'route' => NULL,
                'parameters' => '',
            ),
            
            array (
                'id' => 18,
                'menu_id' => 1,
                'title' => 'Drivers',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => '#80ff00',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2018-01-23 14:04:25',
                'updated_at' => '2018-02-14 16:05:20',
                'route' => NULL,
                'parameters' => '',
            ),
            
            array (
                'id' => 21,
                'menu_id' => 1,
                'title' => 'Courier Options',
                'url' => '/admin/courier-options',
                'target' => '_self',
                'icon_class' => 'voyager-window-list',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2018-01-30 09:59:31',
                'updated_at' => '2018-02-14 16:05:20',
                'route' => NULL,
                'parameters' => '',
            ),
            
            array (
                'id' => 22,
                'menu_id' => 1,
                'title' => 'Clients',
                'url' => '/admin/clients',
                'target' => '_self',
                'icon_class' => 'voyager-book',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2018-02-14 16:17:33',
                'updated_at' => '2018-02-14 16:17:33',
                'route' => NULL,
                'parameters' => NULL,
            ),
        ));
        
        
    }
}